version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ev-calculator-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ev_calculator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ev-calculator-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ev_calculator"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ev-calculator-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/ev_calculator
      # Add other environment variables as needed
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ev-calculator-network

volumes:
  postgres_data:

networks:
  ev-calculator-network:
    driver: bridge